"""
WHAT THIS FILE DOES:
────────────────────
Defines Pydantic schemas for validating API inputs and shaping API outputs.

SKILL LEARNED — Pydantic Schemas vs SQLAlchemy Models:
  This is one of the most important patterns in FastAPI.

  SQLAlchemy Model (app/models/models.py):
    → Defines what's STORED in the database
    → Has database-specific stuff (foreign keys, relationships, indexes)
    → NOT for direct use in API input/output

  Pydantic Schema (this file):
    → Defines what the API ACCEPTS and RETURNS
    → Validates input automatically (wrong type → 422 error with details)
    → Shapes output (control exactly which fields to expose)
    → Completely separate from DB — you control the contract

  WHY SEPARATE?
    Security: You don't want to expose db internals (e.g., auto-increment IDs,
    internal flags, hashed passwords) directly to the API consumer.
    Validation: Pydantic enforces types, min/max values, regex patterns.
    Flexibility: API shape can differ from DB shape.

  PATTERN:
    XxxCreate  = schema for creating (POST body — no ID yet)
    XxxResponse = schema for reading (GET response — has ID)
    XxxUpdate  = schema for partial updates (PATCH body — all optional)
"""

from typing import Optional, List
from pydantic import BaseModel, EmailStr, Field
from datetime import datetime


# ─── Candidate Schemas ────────────────────────────────────────────────────────

class CandidateCreate(BaseModel):
    """What the client sends when creating a new candidate."""
    name: str = Field(..., min_length=1, max_length=100, description="Full name")
    email: EmailStr  # Pydantic validates email format automatically!
    phone: Optional[str] = None
    resume_text: Optional[str] = Field(None, description="Raw resume text for LLM analysis")


class CandidateResponse(BaseModel):
    """What the API returns when a candidate is fetched."""
    id: int
    name: str
    email: str
    phone: Optional[str]
    years_experience: Optional[float]
    skills: Optional[str]
    ai_summary: Optional[str]
    created_at: datetime

    class Config:
        # This allows Pydantic to read data from SQLAlchemy model objects
        # Without this, Pydantic can't read ORM objects (only dicts)
        from_attributes = True


# ─── Job Posting Schemas ──────────────────────────────────────────────────────

class JobPostingCreate(BaseModel):
    """Client sends this to create a job posting."""
    title: str = Field(..., min_length=1, max_length=200)
    company: str = Field(..., min_length=1, max_length=200)
    description: str = Field(..., min_length=10, description="Full job description text")
    required_skills: Optional[str] = Field(None, description="Comma-separated skills")
    min_experience_years: Optional[float] = Field(None, ge=0, le=50)  # ge=0 means >= 0
    location: Optional[str] = None
    is_remote: bool = False


class JobPostingResponse(BaseModel):
    id: int
    title: str
    company: str
    description: str
    required_skills: Optional[str]
    min_experience_years: Optional[float]
    location: Optional[str]
    is_remote: bool
    ai_generated: bool
    is_active: bool
    created_at: datetime

    class Config:
        from_attributes = True


# ─── Resume Analysis Schemas ──────────────────────────────────────────────────

class ResumeAnalysisRequest(BaseModel):
    """Client sends candidate_id to trigger LLM resume analysis."""
    candidate_id: int
    # Optional: re-analyze even if analysis exists
    force_reanalyze: bool = False


class ResumeAnalysisResponse(BaseModel):
    """The structured result of the LLM's resume analysis."""
    candidate_id: int
    candidate_name: str
    
    # The full parsed JSON from the LLM response
    extracted_skills: List[str]
    experience_years: Optional[float]
    education_level: Optional[str]
    
    # Strength/weakness lists generated by LLM
    strengths: List[str]
    areas_for_improvement: List[str]
    
    # Overall suitability score
    overall_score: float = Field(..., ge=0, le=100)
    
    # Human-readable summary generated by LLM
    summary: str
    
    # Metadata
    model_used: str
    analysis_id: int

    class Config:
        from_attributes = True


# ─── Job Match Schemas ────────────────────────────────────────────────────────

class JobMatchRequest(BaseModel):
    """Client sends this to request matching a candidate to a job."""
    candidate_id: int
    job_id: int


class BulkMatchRequest(BaseModel):
    """Match one candidate against multiple jobs, or rank many candidates for one job."""
    job_id: int
    # Optional: if provided, rank only these candidates; else rank all active candidates
    candidate_ids: Optional[List[int]] = None
    top_n: int = Field(10, ge=1, le=100, description="Return top N matches")


class JobMatchResponse(BaseModel):
    """The result of matching a candidate to a job."""
    match_id: int
    candidate_id: int
    candidate_name: str
    job_id: int
    job_title: str
    
    match_score: float = Field(..., ge=0, le=100)
    skills_score: Optional[float]
    experience_score: Optional[float]
    education_score: Optional[float]
    
    match_reasoning: str
    missing_skills: List[str]

    class Config:
        from_attributes = True


class RankedCandidateResponse(BaseModel):
    """One candidate in a ranked list for a job."""
    rank: int
    candidate_id: int
    candidate_name: str
    candidate_email: str
    match_score: float
    skills_score: Optional[float]
    experience_score: Optional[float]
    match_reasoning: str
    missing_skills: List[str]


# ─── Job Description Generation Schemas ──────────────────────────────────────

class JDGenerationRequest(BaseModel):
    """Client sends job requirements, LLM generates a professional JD."""
    job_title: str = Field(..., description="e.g. 'Senior Python Developer'")
    company_name: str
    required_skills: List[str] = Field(..., min_length=1)
    experience_years: int = Field(..., ge=0, le=30)
    location: Optional[str] = None
    is_remote: bool = False
    # Additional context to make the JD more specific
    extra_context: Optional[str] = Field(None, description="e.g. 'startup environment, fast-paced'")
    save_to_db: bool = Field(True, description="Save the generated JD as a JobPosting")


class JDGenerationResponse(BaseModel):
    """The generated job description."""
    job_title: str
    company_name: str
    generated_description: str
    # If saved, returns the job posting ID
    job_posting_id: Optional[int] = None


# ─── Candidate Screening Schemas ──────────────────────────────────────────────

class ScreeningRequest(BaseModel):
    """Generate screening questions for a candidate-job pair."""
    candidate_id: int
    job_id: int
    num_questions: int = Field(5, ge=1, le=15)


class ScreeningResponse(BaseModel):
    """AI-generated screening questions tailored to candidate + job."""
    candidate_name: str
    job_title: str
    questions: List[str]
    focus_areas: List[str]  # What the questions are designed to assess


# ─── Analytics Schema ─────────────────────────────────────────────────────────

class AnalyticsSummary(BaseModel):
    """Dashboard-style analytics summary."""
    total_candidates: int
    total_jobs: int
    total_matches: int
    avg_match_score: Optional[float]
    top_skills_in_demand: List[str]
    top_candidate_skills: List[str]
